<!DOCTYPE html>
<html lang="en">
<head>
    <title>Admin</title>
    <link rel="stylesheet" href="/css/style.css">
</head>

<body>
<h2>Вы вошли как администратор</h2>
<br>
<a href="/user/menu">войти как обычный пользователь</a>
<br>
<a href="/admin/accounts">посмотреть список аккаутов</a>
<br>
<a href="/admin/users">посмотреть список пользователей</a>
<br>
<a href="/logout">выйти из профиля</a>
</body>
</html>