CREATE TABLE IF NOT EXISTS user_images (
    id bigint generated by default as identity,
    bytes bytea,
    content_type varchar(255),
    original_file_name varchar(255),
    size bigint,
    user_id bigint,
    primary key (id)
);